apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: postgresql
spec:
  storageClassName: n1k8s-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi