apiVersion: apps/v1
kind: Deployment
metadata:
   name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
template:
metadata:
labels:
app: postgresql
spec:
volumes:
- name: postgres-pv-storage
persistentVolumeClaim:
claimName: postgres-pv-claim
containers:
- name: postgresql
image: postgres:11
imagePullPolicy: IfNotPresent
ports:
- containerPort: 5432
env:
- name: POSTGRES_PASSWORD
valueFrom:
secretKeyRef:
name: postgres-secret-config
key: password
- name: PGDATA
value: /var/lib/postgresql/data/pgdata
volumeMounts:
- mountPath: /var/lib/postgresql/data
name: postgres-pv-storage

## https://www.sumologic.com/blog/kubernetes-deploy-postgres/
