apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: centos-data
  namespace: centos-linux
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi