apiVersion: v1
kind: Namespace
metadata:
  name: centos-linux
  labels:
    app: centos-linux

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  centos-linux
  namespace: centos-linux
  labels:
    app:  centos-linux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos-linux

  template:
    metadata:
      name: centos-linux
      labels:
        app:  centos-linux

    spec:
      containers:
        - name:  centos-linux
          image: humberzam/centos7-linux:v1
          command: ["/bin/sleep", "3650d"]
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 150m
              memory: 150Mi

          ports:
          - name:  centos-linux
            protocol: TCP
            containerPort: 22

---

apiVersion: v1
kind: Service
metadata:
  namespace: centos-linux
  name: centos-srv
  labels:
    ambiente: desarrollo
    desarrollador: humberto-zamora
    proposito: servicio_de_conexion_con_centos-linux

spec:
  type: ClusterIP
  selector:
    labelsvc: centos-srv
  ports:
  - name: ssh-centos
    protocol: TCP
    port: 22
    targetPort: 22