---
apiVersion: v1
kind: Service
metadata:
  name: prestashop-service
  namespace: app-prestashop
  labels:
    name: k8s-prestashop
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    name: k8s-prestashop
    tier: frontend
