kind: ConfigMap
apiVersion: v1
metadata:
  name: bind9-config
  namespace: bind9
data: 
  named.conf: |-
    acl "trusted" {
      192.168.100.0/24;
      localhost;
      localnets;
    };
    options {        
      directory "/var/bind";
      dump-file "/var/bind/data/cache_dump.db";
      dnssec-validation no;
      dnssec-enable no;
      listen-on {
        any;
        };
      allow-query {
        any;
    };
    forwarders {
            8.8.8.8;
            8.8.4.4;
    };
    pid-file "/var/run/named/named.pid";
    allow-recursion { any; };
          allow-query-cache { any; };
    recursion yes;
    };
    zone "darknet.net" IN {
      type master;
      file "/etc/bind/zones/darknet.net.db";
    };