apiVersion: v1
kind: Service
metadata:
  name: bind-service
  namespace: bind9
spec:
  type: LoadBalancer
  selector:
    app: bind
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      