---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configs
  namespace: istio
data:
  echo.conf: |
    location /h {
      default_type text/html;
      echo_duplicate 1 $echo_client_request_headers;
    }
  proxy-headers.conf: |
      proxy_connect_timeout   90s;
      proxy_send_timeout      90s;
      proxy_read_timeout      90s;
      proxy_buffers           32 4k;
      proxy_buffer_size       8k;
      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        Proxy "";
      proxy_headers_hash_bucket_size 64;
  home.conf: |
      location /app {
        default_type text/html;
        echo "Hola Mundo";
      }