apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hdd-etcd
  labels:
    type: local
spec:
  storageClassName: sistemaficheros
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /HDD-Pods/etcd

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hdd-etcd # Este nombre debe coincidir con claimName.
spec:
  storageClassName: sistemaficheros
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 450Mi

---

apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
spec:
  volumes:
    - name: etcd-storage  # Este nombre debe coincidir con el nombre del volumeMounts.
      persistentVolumeClaim:
        claimName: pvc-hdd-etcd # Este nombre debe coincidir con el nombre del PVC.
  containers:
    - name: task-pv-container
      image: nginx

      resources:
            requests:
               cpu: 20m
               memory: 200Mi
            limits:
              cpu: 30m
              memory: 300Mi

      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: etcd-storage  # Este nombre debe coincidir con el nombre del volumeMounts.
