apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kube-istio-gateway
  namespace: hdd-istio
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - '*'