---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-claim-nfs 
  namespace: hdd-istio
  labels:
    app: nginx
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: training-nfs-pv