---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: training-nfs-pv
  labels:
    pv: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.7
    path: "/nfs/training"