---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
    env: development
  name: nginx
  namespace: istio
spec:
  containers:
  - name: nginx  
    
    image: nginx
    imagePullPolicy: Always
    
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: 20m
        memory: 150Mi

    ports:
    - name: http
      protocol: TCP
      containerPort: 80

    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: hdd-istio

  volumes:
  - name: hdd-istio
    persistentVolumeClaim:
      claimName: hdd-istio

# args: ['ping -i 60 127.0.0.1']