---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-claim
  namespace: istio
  labels:
    app: nginx
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: hdd-istio
