---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: istio
spec:
  selector:
    app: nginx
    env: production
  ports:
  - name: "http"
    protocol: TCP
    port: 8080
    targetPort: 8080
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-svc-node
#   namespace: training
# spec:
#   type: NodePort
#   selector:
#     app: nginx
#     env: production
#   ports:
#   - name: http2
#     protocol: TCP
#     port: 80
#     nodePort: 31423
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-svc-lb
#   namespace: training
# spec:
#   type: LoadBalancer
#   selector:
#     app: nginx
#     env: production
#   ports:
#   - name: http
#     protocol: TCP
#     port: 80
    