apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: training
spec:
  type: NodePort
  selector:
    labelsvc: svcpods
  ports:
  - name: http
    protocol: TCP
    port: 8085
    targetPort: 80
