# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
  # name: nfs-provisioner
# provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
# volumeBindingMode: WaitForFirstConsumer

#---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
  # name: data-
  # labels:
    # type: local
# spec:
  # storageClassName: nfs-client
  # claimRef:
    # name: jenkins-pv-claim
    # namespace: devops-tools
  # capacity:
    # storage: 5Gi
  # accessModes:
    # - ReadWriteOnce
  # local:
    # path: /mnt
  # nodeAffinity:
    # required:
      # nodeSelectorTerms:
      # - matchExpressions:
        # - key: kubernetes.io/hostname
          # operator: In
          # values:
          # # - worker-node01

# # ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-data
  namespace: jenkins
spec:
  storageClassName: n1k8s-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi