apiVersion: v1
kind: Service
metadata:
  namespace: redis
  name: redis-srv
  labels:
    ambiente: desarrollo
    desarrollador: humberto-zamora
    proposito: servicio_de_conexion_con_redis


## Servicios: 
## NodePort >= 30000
## ClusterIP
## 
## 
spec:
  type: LoadBalancer
  selector:
    labelsvc: redis-srv
  ports:
  - name: redis
    protocol: TCP
    port: 6379
#    nodePort: 6379
    targetPort: 6379

## Comandos de acceso:
##    Obtenemos informacion del servicio 
##       k get svc -o wide
##    obtenemos la ip del cluster
##       minikube ip
## Conectamos a Redis
##    redis-cli -h 172.16.175.137 -p 30001


## https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-strong-getting-started-strong-
## https://kubernetes.io/es/docs/concepts/overview/working-with-objects/namespaces/
## 
## https://www.ibm.com/docs/en/cloud-private/3.1.1?topic=networking-kubernetes-service-types

## git clone https://github.com/benc-uk/kubeview
## cd kubeview/charts/
## helm install kubeview kubeview